# Use root/example as user/password credentials
version: '3.1'

services:
  taskapi:
    build: ./taskAPI/
    restart: always
    ports:
      - 3000:3000
  frontend:
    build: ./taskAPI-react-interface/.
    restart: always
    ports:
      - 4000:80
  
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: task

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  